version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: nexus-postgres
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: nexus
      POSTGRES_DB: nexus_sync
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexus"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:8.2
    container_name: nexus-redis
    ports:
      - "56379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
volumes:
  pgdata:
  redisdata:

